[gui]
width = 1440
height = 720
scene_width = 1440 #600
scene_height = 720 #200
roll_x = 30
roll_y = 30
base_dir = "D:\\Projekty\\Python\\sp-seg-tool\\dev-resources"
transparency_factor = 130
depth_gamma_factor = 1.1

[toolbar]